### ISSUE TITLE
`render_snapshot` now throws `rayvertex` error

### ISSUE THREAD

**Issue by AMBarbosa** [h-a-graham/rayvista#43]
Hi! This was working fine until a few months ago, but now I'm getting an error which also appears with the first example in your README file:

```
library(rayshader) 
library(rayvista)

.lat <- 57.219566
.long <- -6.092690

cuillins <- plot_3d_vista(lat = .lat, long = .long, phi=30, outlier_filter=0.001)

render_label(heightmap= cuillins, text='Bla Bheinn: 928 m', lat = .lat,
             long=.long, extent = attr(cuillins, 'extent'),altitude=600,
             clear_previous = T, zscale = 2)

render_compass() 

render_scalebar(limits=c(
  round(dim(cuillins)[2]*attr(cuillins, 'resolution')/1000,1)),
  label_unit = 'km')

render_snapshot(clear=TRUE)


# Error in rayvertex::text3d_mesh(label = temp_label[j, 1], position = c(temp_center[j,  : 
# unused argument (color = temp_color[j, 1:3])
```

Also, if I just run the `cuillins <- plot_3d_vista()` command and then skip directly to `render_snapshot()`, RStudio crashes. Tried several times, with both the latest CRAN versions and the latest GitHub versions of the packages. Cheers!

**Comment by h-a-graham** [comment]
hmm... it looks like this has been an issue in rayshader for a while. https://github.com/tylermorganwall/rayshader/issues/340 

I'll admit to being quite removed from this package now and probably won't have time to investigate what's going with rayshader too deeply. 

A couple of ideas... 

have you tried installing rayvertex from github? 
```
# install.packages("devtools")
devtools::install_github("tylermorganwall/rayvertex")
```

No idea if that will help but the issue does seem to originate from rayvertex so maybe... 

As the issue seems to be with rayvertex, which appears to drive the creation of most of the feature rendering - labels, scalebars etc. I suspect these features won't work until the rayvertex issue is resolved. 

re. the crashing, does this occur with both: 
`render_snapshot(software_render = TRUE)` and `render_snapshot(software_render=FALSE)` ?

**Comment by AMBarbosa** [comment]
Thanks for your prompt reply! Yes, I tried with both the latest CRAN versions and the latest GitHub versions of these packages. And yes, the crash occurs with both `software_render` options. Anyway, it is indeed an issue between `rayshader` and `rayvertex`, though it also breaks your `rayvista` README file. I'll submit the issue there. Cheers!

**Comment by tylermorganwall** [comment]
This should be fixed in the latest version of rayshader/rayvertex: install rayshader via remotes to pull rayshader plus all it's updated dependencies and it should work.

**Comment by AMBarbosa** [comment]
Hi! I had installed rayshader, rayvista and rayvertex from GitHub (with dependencies=TRUE), but the problem persisted. Now I installed them from GitHub again, but this time also updating all dependencies to their GitHub versions, rather than accepting only CRAN updates. I no longer get the error, but the text labels are now so small they become illegible -- here's the output from the same rayvista README example as above:

<img width="759" height="722" alt="Image" src="https://github.com/user-attachments/assets/3f7890bb-ec69-4247-8c1c-9546fd363b49" />

I've tried significantly increasing the `textsize` argument to `rayshader::render_label()`, but it doesn't change. Here's my session info:

```
> sessionInfo()
R version 4.5.1 (2025-06-13)
Platform: x86_64-pc-linux-gnu
Running under: Linux Mint 21.1

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/openblas-pthread/libblas.so.3 
LAPACK: /usr/lib/x86_64-linux-gnu/openblas-pthread/libopenblasp-r0.3.20.so;  LAPACK version 3.10.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=pt_PT.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=pt_PT.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=pt_PT.UTF-8 LC_IDENTIFICATION=C       

time zone: Europe/Lisbon
tzcode source: system (glibc)

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rayvista_0.1.7.4  rayshader_0.38.13

loaded via a namespace (and not attached):
 [1] xfun_0.53          raster_3.6-32      htmlwidgets_1.6.4 
 [4] remotes_2.5.0      processx_3.8.6     lattice_0.22-5    
 [7] callr_3.7.6        vctrs_0.6.5        tools_4.5.1       
[10] ps_1.9.1           curl_7.0.0         parallel_4.5.1    
[13] rgl_1.3.29         proxy_0.4-27       pkgconfig_2.0.3   
[16] KernSmooth_2.23-26 RColorBrewer_1.1-3 desc_1.4.3        
[19] lifecycle_1.0.4    compiler_4.5.1     farver_2.1.2      
[22] textshaping_1.0.1  progress_1.2.3     terra_1.8-70      
[25] codetools_0.2-19   htmltools_0.5.8.1  class_7.3-23      
[28] rayimage_0.19.1    crayon_1.5.3       classInt_0.4-11   
[31] slippymath_0.3.1   elevatr_0.99.1     magick_2.9.0      
[34] iterators_1.0.14   foreach_1.5.2      digest_0.6.37     
[37] sf_1.0-21          purrr_1.1.0        fastmap_1.2.0     
[40] grid_4.5.1         cli_3.6.5          magrittr_2.0.4    
[43] maptiles_0.10.0    base64enc_0.1-3    dichromat_2.0-0.1 
[46] pkgbuild_1.4.8     e1071_1.7-16       prettyunits_1.2.0 
[49] scales_1.4.0       sp_2.2-0           httr_1.4.7        
[52] progressr_0.16.0   ragg_1.4.0         png_0.1-8         
[55] hms_1.1.3          evaluate_1.0.5     knitr_1.50        
[58] rayvertex_0.13.1   doParallel_1.0.17  rlang_1.1.6       
[61] Rcpp_1.1.0         glue_1.8.0         geosphere_1.5-20  
[64] DBI_1.2.3          rstudioapi_0.17.1  jsonlite_2.0.0    
[67] R6_2.6.1           systemfonts_1.3.0  units_0.8-7 
```

**Comment by tylermorganwall** [comment]
That's just one limitation of the software rendering path, which has no concept of screen space and thus can't translate the exact size of the text to the software rendered version. Specify a custom text_size (e.g. `text_size = 120`) to increase the text size. I would also recommend turning on anti-aliasing (`fsaa = 2`) to smooth out some of the jagged edges you see.

Alternatively, it's faster and easier to render with rgl `render_snapshot(software_render = FALSE)` if you don't need to run headless. Then you'll get exactly what is rendered on screen.

**Comment by AMBarbosa** [comment]
This same code was producing normal-looking labels up to a few months ago (I'm guessing up to the `rayvertex` breaking changes). Now, `fsaa = 2` indeed increases the quality of the image (thanks!), but the labels are still illegible, and the `textsize` argument doesn't produce any visible effect. Do you get normal-looking labels with the code above, like the ones shown after the first example in the `rayvista` README? And do your outputs respond to changing the `textsize` argument in this same code? Cheers

**Comment by tylermorganwall** [comment]
Did you enter `textsize`, or `text_size`?

**Comment by AMBarbosa** [comment]
`textsize`, which is what `?render_label` says. `text_size` yields Error "_unused argument (text_size = 120)_".

**Comment by tylermorganwall** [comment]
The `text_size` argument for software rendering is in `render_snapshot()`, see https://www.rayshader.com/reference/render_snapshot.html

**Comment by AMBarbosa** [comment]
Aaaah! You could have specified (^_^;) It is a bit confusing that the text size argument was *not* for the `render_label` function. And I'm still unclear as to why this argument does not have a visible effect (though it exists) there.
